### ISSUE TITLE
[Bug]: Test

### ISSUE THREAD

**Issue by 0xPasho** [MarketingPipeline/Awesome-Repo-Template#1]
### Contact Details

test

### What happened?

A bug happened!Test

### What type of browser are you seeing the problem on?

Safari

### What type of Operating System are you seeing the problem on?

Windows

### Code to produce this issue.

```shell
Test
```

**Comment by MarketingPip** [comment]
@0xPasho - it appears the fix for this is to STAR this repo :wink:

**Comment by 0xPasho** [comment]
@MarketingPip nice work bro
